# User Roles
ROLE_SUPPORTED_USER = "supported_user"
ROLE_CAREGIVER = "caregiver"
ROLE_ADMIN = "admin"

# Notification Types
NOTIFICATION_TYPE_SOS = "SOS"
NOTIFICATION_TYPE_EMERGENCY = "EMERGENCY"
NOTIFICATION_TYPE_GEOFENCE_EXIT = "GEOFENCE_EXIT"
NOTIFICATION_TYPE_BAND_DISCONNECTED = "BAND_DISCONNECTED"
NOTIFICATION_TYPE_SEPARATION_DETECTED = "SEPARATION_DETECTED"
NOTIFICATION_TYPE_ROUTINE_REMINDER = "ROUTINE_REMINDER"
NOTIFICATION_TYPE_LEARNING_REMINDER = "LEARNING_REMINDER"
NOTIFICATION_TYPE_TRANSITION_REMINDER = "TRANSITION_REMINDER"
NOTIFICATION_TYPE_NEW_DM = "NEW_DM"
NOTIFICATION_TYPE_GROUP_MESSAGE = "GROUP_MESSAGE"
NOTIFICATION_TYPE_GROUP_INVITE = "GROUP_INVITE"
NOTIFICATION_TYPE_COMMENT = "COMMENT"
NOTIFICATION_TYPE_REACTION = "REACTION"

# File Upload Configurations
ALLOWED_EXTENSIONS = {
    # Images
    "jpg", "jpeg", "png", "gif", "webp",
    # Documents
    "pdf", "doc", "docx", "txt", "csv",
    # Audio
    "mp3", "wav", "m4a", "ogg"
}
